### ISSUE TITLE
Frame Rerender Loop

### ISSUE THREAD

**Issue by javaarchive** [arduano/Zenith-MIDI#2]
![image](https://user-images.githubusercontent.com/20248577/57000761-e341f700-6b69-11e9-9f1d-37fc55c1dada.png)
It seems like Zenith keeps rendering the same frame over and over again. This occurs in the latest version of Zenith. 

The speed seems to be slowing down and it seems like it's at the end of the midi

**Comment by arduano** [comment]
This could be an issue with tempo events. There is no way zenith will get stuck for no reason as it's adding more ticks to the current time each frame (unless it's paused, but it can't be as it's rendering). Is it an issue with that specific midi? Or does it happen with other midis as well?

**Comment by javaarchive** [comment]
This Midi
https://www.youtube.com/watch?v=vTYn4dJh2Ps
I think it's one of the record midis

**Comment by arduano** [comment]
Does it only happen with this midi or any midi though?

**Comment by javaarchive** [comment]
Only this midi, since I got another midi to render correctly.
Plugin: The normal default plugin(the one of gradients)
Quality: 4k
FPS: 120fps
SAA: 2

**Comment by arduano** [comment]
I tried rendering with the same parameters myself, it rendered just fine. Are you sure this isn't related to some other potential issue? Maybe ffmpeg being weird? Try ticking "ffmpeg debug" before rendering and see if there are any errors. Also try rendering with other settings, as I personally can't re-produce this error and therefore can't test it myself. (sorry for responding late btw)

**Comment by javaarchive** [comment]
It's defintely my computer. This issue happens whenever I keep zenith in the background. 

Also when the loop is happening the Zenith render window stops responding

it seems to work in the previous stable release

**Comment by arduano** [comment]
I keep getting reports about how sometimes the render window stops responding and locks up, however I never manged to reproduce it myself. My guess is it's somehow related to the new render syncing algorithm that syncs the parser with the renderer in a more efficient way to save RAM. I still can't figure out what exactly could be going wrong though.

**Comment by javaarchive** [comment]
So this is what I do. 
I know rendering takes a lot of time, so I just launch Zenith, and once it starts rendering for a bit, I minimize the windows. Then, like an hour later, I pull up the render window and Windows says it stopped responding. Also, the rendered result is squished into the top left corner of the window somehow.

**Comment by arduano** [comment]
Does that happen specifically at 4k 120? Or any resolution?

**Comment by javaarchive** [comment]
I think so. I rendered the same midi at 25 fps 1080p and it worked.

**Comment by arduano** [comment]
If you have time, try 1080p 60, 1080p 120, 4k 60. Also did you say that it only happens when you minimise Zenith?

I'll try rendering 4k 120 again for now, and minimise Zenith.

**Comment by arduano** [comment]
Oh also, what render settings are you using? Default? If so try crf 17 (which is what I recommend using). But also tell me what you were using before.

**Comment by javaarchive** [comment]
I was using the PFA+ plugin at default settings. I added a background image also.

I don't have access to my good computer right now, so I'll have to try rendering tomorrow.

**Comment by arduano** [comment]
Yeah ok. Next time you get access (if you want to help me test this, as I can't do it myself), try re-producing the error while changing the least amount of settings from default. I need to know exactly what setting is causing the issue.

**Comment by javaarchive** [comment]
As soon as possible I'll try to screen record what happens

**Comment by javaarchive** [comment]
I attempted to purposely recreate this but I failed...

**Comment by arduano** [comment]
Hmm weird yeah... I'l close this for now, if you get some more evidence, feel free to re-open it.

**Comment by javaarchive** [comment]
![image](https://user-images.githubusercontent.com/20248577/57903176-b22c1c80-7821-11e9-8e05-78254046bead.png)
![image](https://user-images.githubusercontent.com/20248577/57903183-bb1cee00-7821-11e9-8f4f-5b2d356e8112.png)
Just keeps outputing the same output
Settings: 120fps 1080p preset
SAA: 2
Using Black Midi of flight of the bamboo cutter (so not midi issue)
I used the preview 3 times

PFA default settings except changed note screen time to go slower

**Comment by arduano** [comment]
wdym by same output? Also if you are talking about the % thing on the console window, that thing is designed to go 5 seconds past where all the notes have ended. So if it's 120fps it will go 600 frames after all the last notes leave the screen. However some midis are also very inaccurate with the time as their track end events are really far away for whatever reason.

Anyway, what exactly is the problem?

**Comment by javaarchive** [comment]
So I resized Zenith for like 30 seconds, and then it stops responding. When I check the console window it keeps printing out the same debug output but the speed keeps decreasing

**Comment by javaarchive** [comment]
High fps no render
![image](https://user-images.githubusercontent.com/20248577/57964879-2f729280-78f1-11e9-83a4-74a2e62ef988.png)

**Comment by arduano** [comment]
Can you explain the exact settings you changed to get that to happen? I've rendered 120 fps before no problem.

**Comment by javaarchive** [comment]
It seems like it happens every time I minimize it for some time, but this time I pressed render and the window popped up and nothing happended. 

I think it’s mostly due to my bad computer hardware or drivers(I doubt they were correct)

**Comment by javaarchive** [comment]
settings 120fps 1080p
I minimized Zenith for a bit by accident, and then unminimized it, and when the midi was done rendering it froze. Luckily the file was ok after pressing stop. 

I think it's possible that minimizing disables an event listener in zenith some how.
