### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by fadfdsaadfd** [arduano/Zenith-MIDI#37]
I'm sorry, but I can't figure how to sound midi ..

**Comment by Kaydax** [comment]
When rendering or when previewing the midi?

**Comment by fadfdsaadfd** [comment]
Both. I can't find sound settings..

**Comment by Kaydax** [comment]
Zenith when previewing uses OmniMIDI for sound output, so you need to install that. If you are rendering a video, zenith does not render audio, you would have to use an external program like KMC or OmniConverter to convert the midi to a wav file or other audio format

**Comment by fadfdsaadfd** [comment]
very thanks. very thanks...... Thank you very much.

**Comment by Kaydax** [comment]
Why was this issue reopened?

**Comment by arduano** [comment]
Imma just close for now

**Comment by theodoresamuelwhiteley-cmyk** [comment]
> Zenith when previewing uses OmniMIDI for sound output, so you need to install that. If you are rendering a video, zenith does not render audio, you would have to use an external program like KMC or OmniConverter to convert the midi to a wav file or other audio format

link?

**Comment by 0XOPx** [comment]
https://github.com/KeppySoftware/OmniMIDIv2

**Comment by 0XOPx** [comment]
https://github.com/KeppySoftware/OmniMIDI

**Comment by 0XOPx** [comment]
> Zenith when previewing uses OmniMIDI for sound output, so you need to install that. If you are rendering a video, zenith does not render audio, you would have to use an external program like KMC or OmniConverter to convert the midi to a wav file or other audio format

it does render audio in render, you need the audio
you don't need an editing software to do it

<img width="900" height="600" alt="Image" src="https://github.com/user-attachments/assets/4e1df86f-3c76-4dad-bd27-cdca526475b0" />

**Comment by Kaydax** [comment]
> > Zenith when previewing uses OmniMIDI for sound output, so you need to install that. If you are rendering a video, zenith does not render audio, you would have to use an external program like KMC or OmniConverter to convert the midi to a wav file or other audio format
> 
> it does render audio in render, you need the audio you don't need an editing software to do it
> 
> <img alt="Image" width="900" height="600" src="https://private-user-images.githubusercontent.com/164915721/546750560-4e1df86f-3c76-4dad-bd27-cdca526475b0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA1ODMwNjgsIm5iZiI6MTc3MDU4Mjc2OCwicGF0aCI6Ii8xNjQ5MTU3MjEvNTQ2NzUwNTYwLTRlMWRmODZmLTNjNzYtNGRhZC1iZDI3LWNkY2E1MjY0NzViMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIwOFQyMDMyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTVhMzcxNGYwZjBhMDk2MGNlOWI5NDY1ZTkzYmQ0MzExZjc3N2U0ODkxMWNjOTU2NjlmMTJiNmI3ZGM1NjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EB69WucoBQ67mekcIo7lroVZbb0kTlrKXlA_k7S25I4">

That is for including already rendered audio in the render. Zenith itself does not convert midi to audio for you

**Comment by 0XOPx** [comment]
@Kaydax I know, you need to make it if you make video.
Playback = KDMAPI (needs OmniMIDI)
