### ISSUE TITLE
Low audio quality

### ISSUE THREAD

**Issue by linn14** [arduano/Zenith-MIDI#38]
Using the "Include Audio" option is weird, i used uncompressed wav, and it sounds like 96kbps AAC.
Is there any way to use more than 300+ kbps AAC?

It sounds so cancer
Video: https://www.youtube.com/watch?v=uLona0HveOc&feature=youtu.be
Audio (Compressed to MP3): https://cdn.discordapp.com/attachments/641738482943000606/779823654397542440/Aimonortsa_Lag_Tester_F1__Danidanijr__Orangepaprika_67_Copy_1.mp3

**Comment by Kaydax** [comment]
You can try and use custom ffmpeg options in order to change the quality encoded. There shouldn't be any quality either since we are just passing in the audio file and encoding as aac with no other options

**Comment by Kaydax** [comment]
I assume you have found a way to fix your issue, so im closing out this ticket. If you have any other questions feel free to ask

**Comment by linn14** [comment]
Yup, thanks, i didnt got notification
