### ISSUE TITLE
Upon opening Zenith, the "You'll need a new app to open this ms-gamingoverlay link" error pops up and doesn't even load the player

### ISSUE THREAD

**Issue by WarpPrime** [arduano/Zenith-MIDI#43]
I installed Zenith MIDI and opened the app, and nothing loaded because I don't have Xbox Game Bar (it is completely broken and can't reinstall it).

**Comment by arduano** [comment]
Sounds like a windows problem. Zenith has no connection to Xbox Game Bar, all it does is it loads the pure opengl library and renders shapes to a glut window.

One issue you might have is that the settings window uses WPF, which uses directx 9, which is known for having random issues (e.g. make sure you don't have msi after burner or RTSS open, as those can sometimes mess with dx9).

Anyway, again, sounds like something unrelated to zenith.
