### ISSUE TITLE
Video outputs only to the red channel, FFmpeg reports bad packet

### ISSUE THREAD

**Issue by minelolpride** [arduano/Zenith-MIDI#57]
While the preview of the render displays with correct colors, the final rendered video appears very red, with no other colors present.
![image](https://user-images.githubusercontent.com/16008698/151114529-4fb5c6c3-6da2-4469-be1f-4d2af58dc723.png)
This is present on a fresh install, and occurs in every module, so I turned to FFmpeg to find this in the output.
![image](https://user-images.githubusercontent.com/16008698/151114917-31b72e87-321f-4f0b-a0f3-1ecefa09a7e7.png)
This appears to happen no matter what my input. (settings, letting the render complete)

Is there maybe a version of FFmpeg that plays nice with Zenith here? The link in the README is dead too, so I cannot check it out.

Zenith version is `2.1.5`
FFmpeg version is `5.0-full_build-www.gyan.dev`

**Comment by arduano** [comment]
That's honestly strange. Are you using default settings? I've never seen this before.

Personally I have version 4.3.1 installed, if you want to try that.

**Comment by minelolpride** [comment]
![image](https://user-images.githubusercontent.com/16008698/151191932-5b0e444a-d7c3-4b4f-b075-c7a0595ceeba.png)
Downgraded to 4.3.1, the error persists. I am unsure if this is specific to my hardware too (Ryzen 7 3700x, EVGA GTX1060 6GB SSC), as when I asked around, I havent seen anyone else run across this as of yet

**Comment by arduano** [comment]
Yeah sorry I'm honestly not sure. I don't know anyone else who can reproduce this issue.

When I open FFMPEG, I set the input stream as raw colour bytes passed through stdin. I set the input colour format too, pretty sure it was either rgb or argb, but point is that it's set to the right one and should correctly work.

In your screenshot, I see that the error message comes from the `rawvideo` codec, I'm not sure if that one is built into ffmpeg, but if it isn't then maybe you have a codec issue? I'd suggest having a look into that.

**Comment by minelolpride** [comment]
I was tipped off to disable Unicode UTF-8 in the Windows Region Settings, which I had enabled. Turns out, doing just that fixed the issue. Not sure how it relates to this on a lower level, but it's a fix!
![image](https://user-images.githubusercontent.com/16008698/151284742-e83ed59d-b959-4c76-a5e1-c7356a326890.png)

**Comment by arduano** [comment]
that's so weird
