### ISSUE TITLE
What is Color Events and how to use it

### ISSUE THREAD

**Issue by Creepercdn** [arduano/Zenith-MIDI#58]
I find some code of it in a file: [MidiTrack.cs](https://github.com/arduano/Zenith-MIDI/blob/5c65ad63ffe771014156c8ce73108d38f32d3492/BMEngine/MidiTrack.cs#L534)
I think color event is a meta event, and like `FF 0A 00 0F 00 00 FF FF FF FF`
`FF 0A 00 0F` is prefix,
`00` is channel 1,
next byte is useless,
`FF FF FF FF` is rgba(255,255,255,255)

And I add the same event in a test MIDI, but does not work.
This is the event:
![image](https://user-images.githubusercontent.com/47512866/153714409-000d42ad-ef43-42e4-b370-d56f7c858078.png)

This is my test MIDI: 
[1387298_1.zip](https://github.com/arduano/Zenith-MIDI/files/8053534/1387298_1.zip)

How to use it correctly?

**Comment by khang06** [comment]
you can use https://github.com/arduano/MIDIModificationFramework to write color events

**Comment by arduano** [comment]
You can see how color events are encoded in this file:
https://github.com/arduano/MIDIModificationFramework/blob/master/MIDIEvents/ColorEvent.cs

I believe you're not using the channel byte correctly. Keep in mind that 0-16 sets a specific channel in the track, but 7F sets all channels. Also color events only affect their own track.
