### ISSUE TITLE
Zenith has crashed!

### ISSUE THREAD

**Issue by jansaternus** [arduano/Zenith-MIDI#59]
Every time i open Zenith it shows an error message that goes like this:

invalid parameter

System.Collections.ListDictionaryInternal
  at System.IO.__Error.WinIOError(int32 errorCode, String maybeFullPath)
  at Systm.Console.set_Title(String value)
  at Zenith_MIDI.Program.Main(String[] args)

**Comment by PianoArts2007** [comment]
Do you use any antivirus program ?

**Comment by jansaternus** [comment]
> Do you use any antivirus program ?

No i don't use one.

**Comment by jansaternus** [comment]
But i have a Mac and i use CrossOver to run it so i posted another bug that explains what happens when you open it in CrossOver.

**Comment by Kaydax** [comment]
We do not provide support for use on MacOSX nor Linux via wine or CrossOver. If you are having issues then its with those compatibility layer's, not zenith as zenith is windows only.
