### ISSUE TITLE
malware issue

### ISSUE THREAD

**Issue by FurrStopMotions** [arduano/Zenith-MIDI#76]
this is a malware

this tries to do something internet

all threats found on Norton360

**Comment by arduano** [comment]
Is it one of those "heuristic check" or "unpopular program check" flags or something? This is what programs that aren't used by many people have to deal with. Zenith also has a plugin loading system, which some AVs don't like much too. 

But yeah this would definitely be a false positive, the code is open source and you can try decompiling it to verify if it's safe or not.
