### ISSUE TITLE
This is more of an idea and I want feedback

### ISSUE THREAD

**Issue by Kerbal-Man** [arduano/Zenith-MIDI#87]
So I had an idea for a new rendering method where instead of drawing the notes to the screen you bake all the notes into an image and draw that to the screen and move it

**Comment by Kaydax** [comment]
Thats basically what UMP does and its not really better than what zenith currently does

**Comment by Kaydax** [comment]
It's also more limiting and harder to work with. But its possible for someone to make a scripted rendering plugin for zenith that does this

**Comment by Kerbal-Man** [comment]
Wow ok thanks for the anset
