### ISSUE TITLE
Problem in Scripted module

### ISSUE THREAD

**Issue by DotKantum** [arduano/Zenith-MIDI#88]
I had to set Note screen time to a high value to render horizontal piano.
But if I set Note screen time to a high value(eg 4096) and start preview or render, then it's finishes too early.
This problem is only in Scripted module.

**Comment by arduano** [comment]
Hi, Zenith is no longer maintained (especially Zenith 2, Zenith 3 works better but never implemented the scripted module), so I'm not really able to fix this. Feel free to leave the issue open, some modders do work on zenith still, but I don't think the core maintainers here would still be able to help with this.

**Comment by DotKantum** [comment]
Extending the midi will resolve it.
