### ISSUE TITLE
How To I Load Soundfont Files

### ISSUE THREAD

**Issue by 0XOPx** [arduano/Zenith-MIDI#98]
How + Form Releases + 2.1.5

**Comment by 0XOPx** [comment]
![image](https://github.com/user-attachments/assets/5bea8bc5-537e-4e96-ad3c-281fbfcd527d)

**Comment by 0XOPx** [comment]
*sOUNDFONT

**Comment by arduano** [comment]
Zenith doesn't render audio. If you want audio, you'd have to use a different program to generate the audio file and include it when rendering.

If you want audio during preview, you'd need something KDMAPI-compatible such as OmniMIDI. In which case, you'd load the soundfont through that program.

**Comment by 0XOPx** [comment]
but it shows that
i dont support it :(((

pon., 22 lip 2024 o 04:23 Leo ***@***.***> napisał(a):
