### ISSUE TITLE
I WANNA LOAD SF2 FILES AND NOTE COUNTER TO HAVE MIDITRAIL +

### ISSUE THREAD

**Issue by 0XOPx** [arduano/Zenith-MIDI#99]
REAL PLEASE ADD THE INSTRUCTIONS IN COMMENTS
PLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS :((((((

**Comment by arduano** [comment]
🤡

**Comment by 0XOPx** [comment]
Why close (type instructions)

śr., 24 lip 2024, 23:15 użytkownik Leo ***@***.***> napisał:
